"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Building2, CheckCheck, ChevronDown, CircleHelp, Eye, EyeOff, LogOut, Mail, Menu, MessageSquareText, MoreHorizontal, Paperclip, Plus, Search, Send, Settings, ShieldCheck, Star, Tag, Users, X } from "lucide-react";

type Conversation={id:string|number;name:string;email:string;company:string;initials:string;color:string;preview:string;time:string;unread:number;status:string;subject?:string};
type Message={id:number;mine:boolean;text:string;time:string};
const DEMO_EMAIL="admin@khait.app",DEMO_PASSWORD="Khait@2026";
const starterConversations:Conversation[]=[
{id:1,name:"محمد الصوفي",email:"m.alsufi@example.com",company:"متجر رواسي",initials:"م ص",color:"#5c6ac4",preview:"وصلت الحوالة، هل يمكن تنفيذ الطلب اليوم؟",time:"10:42",unread:2,status:"طلب مفتوح"},
{id:2,name:"سارة القحطاني",email:"sarah@noor.sa",company:"نور للتجارة",initials:"س ق",color:"#9d6f42",preview:"شكرًا، تم استلام الفاتورة بنجاح.",time:"أمس",unread:0,status:"تم الحل"},
{id:3,name:"أحمد الحكيمي",email:"ahmed@almadar.co",company:"المدار",initials:"أ ح",color:"#267c6e",preview:"نحتاج عرض سعر لخمسين بطاقة.",time:"أمس",unread:1,status:"بانتظار الرد"}];
const starterMessages:Record<string,Message[]>={1:[{id:1,mine:false,text:"السلام عليكم، قمنا بتحويل المبلغ المطلوب صباح اليوم.",time:"10:31"},{id:2,mine:false,text:"وصلت الحوالة، هل يمكن تنفيذ الطلب اليوم؟",time:"10:32"},{id:3,mine:true,text:"وعليكم السلام يا محمد، وصلت رسالتك. سأراجع الحوالة مع الحسابات وأؤكد لك خلال دقائق.",time:"10:36"}],2:[{id:4,mine:false,text:"شكرًا، تم استلام الفاتورة بنجاح.",time:"أمس"}],3:[{id:5,mine:false,text:"نحتاج عرض سعر لخمسين بطاقة.",time:"أمس"}]};

export default function Home(){
 const[ready,setReady]=useState(false),[loggedIn,setLoggedIn]=useState(false),[loginEmail,setLoginEmail]=useState(""),[loginPassword,setLoginPassword]=useState(""),[showPassword,setShowPassword]=useState(false),[loginError,setLoginError]=useState("");
 const[conversations,setConversations]=useState<Conversation[]>(starterConversations),[messages,setMessages]=useState<Record<string,Message[]>>(starterMessages),[selected,setSelected]=useState<string|number>(1),[query,setQuery]=useState(""),[filter,setFilter]=useState("الكل"),[draft,setDraft]=useState(""),[showNew,setShowNew]=useState(false),[mobileList,setMobileList]=useState(true),[sending,setSending]=useState(false),[sendError,setSendError]=useState("");
 const[newName,setNewName]=useState(""),[newEmail,setNewEmail]=useState(""),[newCompany,setNewCompany]=useState(""),[newSubject,setNewSubject]=useState("");
 useEffect(()=>{try{setLoggedIn(localStorage.getItem("khait_session")==="active");const c=localStorage.getItem("khait_conversations"),m=localStorage.getItem("khait_messages");if(c)setConversations(JSON.parse(c));if(m)setMessages(JSON.parse(m));}finally{setReady(true)}},[]);
 useEffect(()=>{if(ready){localStorage.setItem("khait_conversations",JSON.stringify(conversations));localStorage.setItem("khait_messages",JSON.stringify(messages));}},[conversations,messages,ready]);
 useEffect(()=>{if(!loggedIn)return;fetch("/api/conversations").then(r=>r.ok?r.json():Promise.reject()).then(({conversations:rows})=>{if(!rows?.length)return;const cs:Conversation[]=rows.map((r:any)=>{const customer=Array.isArray(r.customers)?r.customers[0]:r.customers;const sorted=[...(r.messages||[])].sort((a:any,b:any)=>new Date(a.created_at).getTime()-new Date(b.created_at).getTime());const last=sorted.at(-1);return{id:r.id,name:customer?.name||customer?.email||"عميل",email:customer?.email||"",company:customer?.notes||"عميل",initials:(customer?.name||customer?.email||"ع").split(" ").slice(0,2).map((p:string)=>p[0]).join(" "),color:"#267c6e",preview:last?.text_body||r.subject,time:last?new Date(last.created_at).toLocaleTimeString("ar",{hour:"2-digit",minute:"2-digit"}):"",unread:0,status:r.status==="closed"?"تم الحل":"طلب مفتوح",subject:r.subject}});const ms:Record<string,Message[]>={};rows.forEach((r:any)=>{ms[r.id]=(r.messages||[]).sort((a:any,b:any)=>new Date(a.created_at).getTime()-new Date(b.created_at).getTime()).map((m:any)=>({id:m.id,mine:m.direction==="outbound",text:m.text_body||m.subject||"(رسالة بلا نص)",time:new Date(m.created_at).toLocaleTimeString("ar",{hour:"2-digit",minute:"2-digit"})}))});setConversations(cs);setMessages(ms);setSelected(cs[0].id)}).catch(()=>{});},[loggedIn]);
 const active=conversations.find(c=>c.id===selected)??conversations[0];
 const filtered=useMemo(()=>conversations.filter(c=>`${c.name} ${c.email} ${c.company}`.toLowerCase().includes(query.toLowerCase())&&(filter==="الكل"||(filter==="غير مقروء"&&c.unread>0)||(filter==="مفتوحة"&&c.status!=="تم الحل"))),[conversations,query,filter]);
 function login(e:FormEvent){e.preventDefault();if(loginEmail.trim().toLowerCase()===DEMO_EMAIL&&loginPassword===DEMO_PASSWORD){localStorage.setItem("khait_session","active");setLoggedIn(true);setLoginError("");}else setLoginError("البريد أو كلمة المرور غير صحيحة");}
 function logout(){localStorage.removeItem("khait_session");setLoggedIn(false);setLoginPassword("");}
 function openConversation(id:string|number){setSelected(id);setMobileList(false);setConversations(items=>items.map(c=>c.id===id?{...c,unread:0}:c))}
 async function sendMessage(){if(!draft.trim()||!active||sending)return;const text=draft.trim();setSending(true);setSendError("");try{const response=await fetch("/api/email/send",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({to:active.email,text,subject:active.subject||"رد من خيط",conversationId:typeof active.id==="string"?active.id:undefined})});const result=await response.json();if(!response.ok)throw new Error(result.error||"تعذر الإرسال");const msg={id:result.messageId||Date.now(),mine:true,text,time:"الآن"};setMessages(all=>({...all,[String(result.conversationId||active.id)]:[...(all[String(active.id)]||[]),msg]}));setConversations(items=>items.map(c=>c.id===active.id?{...c,id:result.conversationId||c.id,preview:text,time:"الآن"}:c));setSelected(result.conversationId||active.id);setDraft("")}catch(error){setSendError(error instanceof Error?error.message:"تعذر الإرسال")}finally{setSending(false)}}
 async function addCustomer(e:FormEvent){e.preventDefault();if(sending)return;setSending(true);setSendError("");try{const response=await fetch("/api/email/send",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({to:newEmail,name:newName,customerCompany:newCompany,subject:newSubject,text:newSubject})});const result=await response.json();if(!response.ok)throw new Error(result.error||"تعذر الإرسال");const id=result.conversationId;const initials=newName.split(" ").slice(0,2).map(p=>p[0]).join(" ");const c:Conversation={id,name:newName,email:newEmail,company:newCompany||"عميل جديد",initials,color:"#2f6f8f",preview:newSubject,time:"الآن",unread:0,status:"طلب مفتوح",subject:newSubject};setConversations(items=>[c,...items]);setMessages(all=>({...all,[String(id)]:[{id:result.messageId||Date.now(),mine:true,text:newSubject,time:"الآن"}]}));setSelected(id);setNewName("");setNewEmail("");setNewCompany("");setNewSubject("");setShowNew(false);setMobileList(false)}catch(error){setSendError(error instanceof Error?error.message:"تعذر الإرسال")}finally{setSending(false)}}
 if(!ready)return <div className="splash">خَيْط</div>;
 if(!loggedIn)return <main className="login-page" dir="rtl"><section className="login-brand"><div className="login-logo">خ</div><div><span>منصة خَيْط</span><h1>بريد شركتك،<br/>بطريقة المحادثات.</h1><p>اجمع رسائل العملاء في مكان واحد، ووزّعها على فريقك، وتابع كل محادثة دون ضياع.</p></div><div className="trust-line"><ShieldCheck/>نسخة تجريبية آمنة — لا ترسل بريدًا حقيقيًا</div></section><section className="login-card"><form onSubmit={login}><p className="eyebrow">تسجيل الدخول</p><h2>مرحبًا بعودتك</h2><p className="login-note">ادخل إلى مساحة عمل شركتك لإدارة محادثات العملاء.</p><label>البريد الإلكتروني<div className="login-input"><Mail/><input type="email" value={loginEmail} onChange={e=>setLoginEmail(e.target.value)} placeholder="name@company.com" autoComplete="username"/></div></label><label>كلمة المرور<div className="login-input"><input type={showPassword?"text":"password"} value={loginPassword} onChange={e=>setLoginPassword(e.target.value)} placeholder="••••••••" autoComplete="current-password"/><button type="button" onClick={()=>setShowPassword(v=>!v)}>{showPassword?<EyeOff/>:<Eye/>}</button></div></label>{loginError&&<div className="login-error">{loginError}</div>}<button className="login-button" type="submit">دخول إلى خَيْط</button><div className="demo-box"><strong>بيانات التجربة</strong><span>{DEMO_EMAIL}</span><span>{DEMO_PASSWORD}</span><button type="button" onClick={()=>{setLoginEmail(DEMO_EMAIL);setLoginPassword(DEMO_PASSWORD)}}>تعبئة البيانات تلقائيًا</button></div></form></section></main>;
 return <main dir="rtl" className="app-shell">
 <aside className="rail"><div className="logo-mark">خ</div><nav><button className="rail-item active"><MessageSquareText/></button><button className="rail-item"><Users/></button><button className="rail-item"><Tag/></button><button className="rail-item"><Building2/></button></nav><div className="rail-bottom"><button className="rail-item"><CircleHelp/></button><button className="rail-item"><Settings/></button><button className="profile-dot" onClick={logout} title="تسجيل الخروج">هـ</button></div></aside>
 <section className={`inbox-panel ${mobileList?"mobile-show":"mobile-hide"}`}><header className="inbox-head"><div><p className="eyebrow">مساحة عمل أمد</p><h1>المحادثات</h1></div><button className="primary-icon" onClick={()=>setShowNew(true)}><Plus/></button></header><div className="search-wrap"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث باسم العميل أو بريده"/></div><div className="filters">{["الكل","غير مقروء","مفتوحة"].map(item=><button key={item} onClick={()=>setFilter(item)} className={filter===item?"selected":""}>{item}</button>)}</div>{sendError&&<div className="login-error">{sendError}</div>}<div className="conversation-list">{filtered.map(c=><button key={c.id} onClick={()=>openConversation(c.id)} className={`conversation-card ${selected===c.id?"selected":""}`}><span className="avatar" style={{background:c.color}}>{c.initials}</span><span className="conversation-copy"><span className="row"><strong>{c.name}</strong><small>{c.time}</small></span><span className="company">{c.company}</span><span className="row"><span className="preview">{c.preview}</span>{c.unread>0&&<b className="unread">{c.unread}</b>}</span></span></button>)}</div></section>
 {active&&<><section className={`chat-panel ${!mobileList?"mobile-show":"mobile-hide"}`}><header className="chat-head"><button className="mobile-back" onClick={()=>setMobileList(true)}><Menu/></button><span className="avatar" style={{background:active.color}}>{active.initials}</span><div className="chat-person"><strong>{active.name}</strong><span>{active.email}</span></div><span className="status-pill"><span/>{active.status}</span><button className="icon-button"><Star/></button><button className="icon-button"><MoreHorizontal/></button></header><div className="thread"><div className="date-divider"><span>اليوم</span></div>{(messages[String(active.id)]||[]).map(m=><div key={m.id} className={`message-row ${m.mine?"mine":"theirs"}`}><div className="bubble"><p>{m.text}</p><span>{m.time}{m.mine&&<CheckCheck/>}</span></div></div>)}</div><footer className="composer"><textarea value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage()}}} placeholder={`اكتب ردًا إلى ${active.name}…`}/><div className="composer-actions"><div><button><Paperclip/></button><button><MoreHorizontal/></button></div><button className="send-button" disabled={sending} onClick={sendMessage}><Send/>{sending?"جارٍ الإرسال…":"إرسال بالبريد"}</button></div><span className="email-note"><Mail/> إرسال فعلي إلى {active.email} والرد يعود إلى نفس المحادثة</span></footer></section>
 <aside className="details-panel"><div className="details-top"><span>بيانات العميل</span><button><LogOut onClick={logout}/></button></div><div className="customer-card"><span className="large-avatar" style={{background:active.color}}>{active.initials}</span><h2>{active.name}</h2><p>{active.company}</p></div><dl><div><dt>البريد الإلكتروني</dt><dd>{active.email}</dd></div><div><dt>رقم العميل</dt><dd>KH-{String(active.id).slice(-4)}</dd></div><div><dt>الموظف المسؤول</dt><dd><span className="mini-avatar">هـ</span> هشام</dd></div><div><dt>حالة المحادثة</dt><dd><button className="select-like">{active.status}<ChevronDown/></button></dd></div></dl><div className="labels"><h3>الوسوم <button><Plus/></button></h3><div><span>عميل مهم</span><span>مبيعات</span></div></div><button className="resolve-button"><CheckCheck/>إغلاق المحادثة</button></aside></>}
 {showNew&&<div className="modal-backdrop" onMouseDown={()=>setShowNew(false)}><form className="new-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={addCustomer}><div className="modal-title"><div><p className="eyebrow">محادثة جديدة</p><h2>إضافة عميل بالبريد</h2></div><button type="button" onClick={()=>setShowNew(false)}><X/></button></div><label>اسم العميل<input required value={newName} onChange={e=>setNewName(e.target.value)} placeholder="مثال: عبدالله محمد"/></label><label>البريد الإلكتروني<input required type="email" value={newEmail} onChange={e=>setNewEmail(e.target.value)} placeholder="customer@example.com"/></label><label>اسم الشركة<input value={newCompany} onChange={e=>setNewCompany(e.target.value)} placeholder="اختياري"/></label><label>أول رسالة<input required value={newSubject} onChange={e=>setNewSubject(e.target.value)} placeholder="اكتب أول رسالة للعميل"/></label><div className="modal-actions"><button type="button" onClick={()=>setShowNew(false)}>إلغاء</button><button className="primary-action" type="submit">إضافة وبدء المحادثة</button></div></form></div>}
 </main>
}
